### ISSUE TITLE
Support for SecuritySystem service?

### ISSUE THREAD

**Issue by schmittx** [tonybrame/homebridge-total-connect-security#1]
Are there any plans to expand the function to support SecuritySystem service within HomeKit (rather than the current Switch service)?

**Comment by tonybrame** [comment]
Not currently... My needs for this were relatively light - I always use "Arm Stay" and "Off" for my system. May be a rainy day project sometime... I have some other plugins that I'm trying to figure out first

**Comment by madegn** [comment]
Any thoughts on adding additional features to Total Connect Security.
